# Generated by Django 4.1.5 on 2023-01-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceman',
            options={'verbose_name_plural': 'Servicemen'},
        ),
        migrations.RemoveField(
            model_name='serviceman',
            name='serviceman_name',
        ),
    ]
