# Generated by Django 4.1.5 on 2023-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceman', '0002_alter_serviceman_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceman',
            name='serviceman_id',
            field=models.ImageField(upload_to='serviceman/license'),
        ),
    ]
