# Generated by Django 4.1.5 on 2023-02-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceman', '0003_alter_serviceman_serviceman_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceman.serviceman'), max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('serviceman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceman.serviceman')),
            ],
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serviceman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceman.serviceman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.mainservice')),
            ],
        ),
    ]
