# Generated by Django 4.1.5 on 2023-02-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceman', '0003_alter_serviceman_serviceman_id'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainservice',
            name='serviceman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serviceman.serviceman'),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='user',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serviceman.serviceman'), max_length=50),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='serviceman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serviceman.serviceman'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.mainservice'),
        ),
    ]
