# Generated by Django 4.1.5 on 2023-02-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_mainservice_serviceman_alter_mainservice_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('service_img', models.ImageField(blank=True, null=True, upload_to='services/img')),
            ],
        ),
    ]
