# Generated by Django 4.1.5 on 2023-02-09 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceman', '0003_alter_serviceman_serviceman_id'),
        ('orders', '0005_alter_order_date_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=80, null=True)),
                ('review', models.TextField(blank=True, max_length=1000, null=True)),
                ('star', models.IntegerField(blank=True, null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('serviceman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceman.serviceman')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
